name: Automated Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm

      - run: pnpm install

      - run: pnpm run build

      - id: files_changed
        uses: tj-actions/verify-changed-files@v8.8
        with:
          files: chinese-holidays.ics

      - if: steps.changed-files.outputs.files_changed == 'true'
        id: date
        run: |
          echo "::set-output name=number::$(date +%Y%m%d%H%M%S)"
          echo "::set-output name=text::$(date +'%F %T')"

      - if: steps.changed-files.outputs.files_changed == 'true'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -am "build: github action auto build at ${{ steps.diff.outputs.text }}"

      - if: steps.changed-files.outputs.files_changed == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'build: github action auto build at ${{ steps.date.outputs.text }}'
          committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          branch: autoupdate/${{ steps.date.outputs.number }}
          delete-branch: true
          title: 'build: github action auto build at ${{ steps.date.outputs.text }}'
          body: 'build: github action auto build at ${{ steps.date.outputs.text }}'
          labels: enhancement
          assignees: baranwang
          reviewers: baranwang
